# Generated by Django 5.1 on 2024-08-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='coupon_applied_amount',
            new_name='amount',
        ),
    ]
