# Generated by Django 5.1 on 2024-08-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_coupon_applied_amount_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
