# Generated by Django 5.1 on 2024-08-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
