# Generated by Django 5.1 on 2024-08-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='request_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
