# Generated by Django 5.1 on 2024-08-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_request_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accept_request',
            field=models.BooleanField(default=False),
        ),
    ]
